### PR TITLE
fade out error box when entering wrong password

### PR DESCRIPTION
**Pull request by MaximilianMeister**
bsc#1064044

Signed-off-by: Maximilian Meister <mmeister@suse.de>

### CODE REVIEW

**Comment by MaximilianMeister** [comment]
[Bug 1064044 — Dex login error message does not clear](https://trello.com/c/hhw2copf/421-bug-1064044-dex-login-error-message-does-not-clear)

**Comment by vitoravelino** [comment]
@MaximilianMeister Did you try this? I think the transition only happens when the property in question changes. In this case we don't change the visibility of the error box.

**Comment by vitoravelino** [comment]
After some research I think we could use animations instead of transitions. Check what I was able to achieve at https://jsbin.com/kuqihoguti/1/edit?html,css,output 

That does the trick, right?

**Comment by vitoravelino** [comment]
This is an workaround that we should get rid off later. I think the correct approach is to redirect the user to another page when user/password matches. 

I think we are gonna replace our login with dex in the future and we won't have this weird behavior for the kubectl config download anymore.

**Comment by MaximilianMeister** [comment]
> Did you try this? I think the transition only happens when the property in question changes. In this case we don't change the visibility of the error box.

i tried it in the browser, and as soon as the popup appears, it will start the countdown to fade away, and then disappears as expected

**Comment by vitoravelino** [comment]
> i tried it in the browser, and as soon as the popup appears, it will start the countdown to fade away, and then disappears as expected

You are right. It indeed when it starts fading out asap as it appears. It made me curious to understand why. Anyway, here are the two approaches:

### transition
transition

### animation
animation

I think waiting a bit and then start fading out seems more friendly for me. What do you think?

**Comment by vitoravelino** [comment]
I think this does the trick.

```css
@-webkit-keyframes fadeOut {
  0%   { opacity: 1; }
  90%  { opacity: 1; }
  99.9% {
    height: 24px;
    margin-bottom: 15px;
    padding: 4px 0;
  }
  100% {
    height: 0px;
    padding: 0;
    margin-bottom: 0px;
    opacity: 0;
  }
}
@keyframes fadeOut {
  0%   { opacity: 1; }
  90%  { opacity: 1; }
  99.9% {
    height: 24px;
    margin-bottom: 15px;
    padding: 4px 0;
  }
  100% {
    height: 0px;
    padding: 0;
    margin-bottom: 0px;
    opacity: 0;
  }
}

.dex-error-box {
  /* other stuff here (...) */
  animation: fadeOut 5s 1;
  -webkit-animation: fadeOut 5s 1;
  animation-fill-mode: forwards;
  -webkit-animation-fill-mode: forwards;
}
```

animation

**Review by vitoravelino — APPROVED** [review]
LGTM

**Pull request merged**
