### PR TITLE
update caasp logo

### PR DESCRIPTION
**Pull request by MaximilianMeister**
bsc#1062247

Signed-off-by: Maximilian Meister <mmeister@suse.de>

### CODE REVIEW

**Comment by MaximilianMeister** [comment]
Before css change:
dex-broken

After css change
dex-correct

@vitoravelino i hope its correct, as i just edited the css in the browser. as i had to copy the assets into the dex containers on the workers which is a bit complicated :-(

**Comment by vitoravelino** [comment]
@MaximilianMeister Don't change any css here. If you check https://github.com/kubic-project/dex-branding/pull/2/files#diff-4dcf2acf8c541f3053560d43823a706e you will see that there's a huge difference on how both images were exported. You just need to match height 60px on the image, not css.

**Review by vitoravelino — APPROVED** [review]
LGTM. Image format and css changes are good. Simplicity ftw!

**Comment by MaximilianMeister** [comment]
> Don't change any css here. If you check https://github.com/kubic-project/dex-branding/pull/2/files#diff-4dcf2acf8c541f3053560d43823a706e you will see that there's a huge difference on how both images were exported. You just need to match height 60px on the image, not css.

~~ok i'll re-export the image with 60px height~~
not needed

**Pull request merged**
